services:
  node-app:
    image: abdelrahman9nasser/node-app:node

    networks:
      - app-network
    depends_on:
    #  - mongo
      - postgres
      - redis
  # mongo:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example 
#     networks:
#       - app-network
#     volumes:
#       - mongo-db:/data/db

# mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#       ME_CONFIG_BASICAUTH_ENABLED: true
#       ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
#       ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
#     networks:
#       - app-network

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app-network
  redis:

    image: redis
    restart: always
    networks:
      - app-network  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
networks:
  app-network:
    driver: bridge
volumes:
  mongo-db: 
  postgres-db: